steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/argocd-repo/sample-python-app:$SHORT_SHA'
    - '.'

# Step 2: Push Docker image
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'asia-south1-docker.pkg.dev/$PROJECT_ID/argocd-repo/sample-python-app:$SHORT_SHA'

# Step 3: Update GitOps repository
- name: 'gcr.io/cloud-builders/git'
  entrypoint: 'bash'
  secretEnv:
    - 'GITHUB_TOKEN'
  args:
    - '-c'
    - |
      set -e

      git config --global user.email "cloudbuild@google.com"
      git config --global user.name "Cloud Build"

      rm -rf sample-python-app-gitops

      git clone https://NISARGA-5:${GITHUB_TOKEN}@github.com/NISARGA-5/sample-python-app-gitops.git

      cd sample-python-app-gitops

      sed -i "s|image: .*|image: asia-south1-docker.pkg.dev/$PROJECT_ID/argocd-repo/sample-python-app:$SHORT_SHA|g" deployment.yaml

      git add deployment.yaml

      git commit -m "Update image to $SHORT_SHA" || exit 0

      git push origin main

availableSecrets:
  secretManager:
    - versionName: projects/project-1-501612/secrets/github-pat/versions/latest
      env: GITHUB_TOKEN

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/argocd-repo/sample-python-app:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
