steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/project-1-501612/argocd-repo/sample-python-app:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/project-1-501612/argocd-repo/sample-python-app:$COMMIT_SHA'

images:
  - 'asia-south1-docker.pkg.dev/project-1-501612/argocd-repo/sample-python-app:$COMMIT_SHA'
